### ISSUE TITLE
use different javascript sources based on environment

### ISSUE THREAD

**Issue by do3meli** [maglub/piLogger#104]
use CDN javascript ressources if it is a production environement.
use local javascript ressources if it is a local environement.
that could be achieved with the stub file

**Comment by maglub** [comment]
Given that we would have a variable set (i.e $localCDN = true;), how would we go at this in the Twig template?

**Comment by do3meli** [comment]
we could define 3 different variables/arrays in `index.php`:

```
$twig->addGlobal('useCDN', true);
$twig->addGlobal('localJS',array( 'path/to/JS/nr/1', 'path/to/JS/nr/2' ));
$twig->addGlobal('CDNJS',array( 'path/to/CDN/JS/nr/1', 'path/to/CDN/JS/nr/2' ));
```
then we could remove all javascript definitions in the `_layout.html` file and add the following:

```
{% if useCDN  %}
   {% for res in CDNJS %}
        <script res="{{ res }}" type="javascript"></script>
    {% endfor %}
{% else %}
      {% for res in localJS %}
        <script res="{{ res }}" type="javascript"></script>
    {% endfor %}
{% endif %}
```

**Comment by maglub** [comment]
Opted for a solution using piLogger/etc/piLogger.conf as control mechanism, and a variable called "isOffline".

```
#-------------------------
# Development status
#-------------------------
isOffline="true"
```

To get this into php, I added a function which reads in this config file:

```
$config = getAppConfig($root . "/../etc/piLogger.conf");
...
$twig->addGlobal('isOffline', (isset($config['isOffline']) && $config['isOffline'] == "true")?true:false);
```
