### ISSUE TITLE
Copy ssh-keys in backup.sh

### ISSUE THREAD

**Issue by maglub** [maglub/piLogger#120]
When making a backup, copy the content of .ssh as well.

**Comment by do3meli** [comment]
my security ring bell is going on like crazy ;-) i think this is maybe not a such a good idea as one would not expect to have a backup file containing ssh private keys.

**Comment by maglub** [comment]
Hmmm, you've got a very good point. But what about your Mac's time-machine backups? Don't they contain your ssh-keys?

I.e, these backup files are owned by the user "pi", and if you get to these files, you already compromized the system and have access to ~/.ssh

I can live without these backed up. It is just annoying, since I forgot to bring over the ssh-keys from my development raspberry pi, and have to go through the 10 seconds to add new keys in github. =)

**Comment by maglub** [comment]
Agreeing with you, skipping this enhancement.
