### ISSUE TITLE
resetPassword does not accept any characters

### ISSUE THREAD

**Issue by do3meli** [maglub/piLogger#138]
the resetPassword function does not accept any characters. for example the resetPassword script will return an error if for example the password contains a closing bracket ")" or something like this "::H!".

**Comment by maglub** [comment]
Works fine, you just have to use ""

```
 ./resetPassword "::H!"
```

Otherwise the shell will expand the character strings.

**Comment by do3meli** [comment]
ok - we will have to mention this somewhere in the readme ;-)

**Comment by maglub** [comment]
Should be part of standard unix knowledge, but ok; never hurts to be clear.

Example:

```
maglub@ubuntu-14:~/dev/www/piLogger/bin$ echo ::H!)
-bash: !: event not found
maglub@ubuntu-14:~/dev/www/piLogger/bin$ echo "::H!"
::H!
maglub@ubuntu-14:~/dev/www/piLogger/bin$ echo "::H!)"
-bash: !: event not found
maglub@ubuntu-14:~/dev/www/piLogger/bin$ echo '::H!)'
::H!)
```
