### ISSUE TITLE
Bug: setup.sh installs apache2 together with php5

### ISSUE THREAD

**Issue by maglub** [maglub/piLogger#139]
When setting up a new system, the setup.sh installs apache2 together with one of the php packages.

This breaks the installation after a reboot, since apache2 is started before lighttpd.

# References

* http://wildlyinaccurate.com/installing-php-on-debian-without-apache/

**Comment by maglub** [comment]
Quote:

You can get around this by installing one of the other dependencies before php5. For example:

```
apt-get install php5-fpm php5 

or 

apt-get install php5-cgi php5.
```

**Comment by do3meli** [comment]
could we not disable the auto startup for apache2?

**Comment by maglub** [comment]
Sure we could, but would only be a workaround and a waste of both bandwidth and space.

We can avoid installing it by using the construct above, installing php5-cgi before php5, see the referenced link.

**Comment by maglub** [comment]
Installing php5-cgi before php5 solved this.

**Comment by maglub** [comment]
New install still install apache2.
