### ISSUE TITLE
app.db does not contain any tables after setup.sh

### ISSUE THREAD

**Issue by do3meli** [maglub/piLogger#14]

**Comment by do3meli** [comment]
1) Run the ddl.sql script

2) Add devices
for device in $(./dbTool --scan 2>/dev/null); do shortDevice=$(basename $device); echo ./dbTool --add -d --deviceType 1wire --deviceId $shortDevice --devicePath $device; done

**Comment by maglub** [comment]
Initial creation of app.sqlite3 database is now in:

1) setup.sh
2) possible to perform by running "./dbTool --setup --db"
