### ISSUE TITLE
adopt code to work with PHP 5.6

### ISSUE THREAD

**Issue by do3meli** [maglub/piLogger#140]
The Debian Jessie repositories now include PHP 5.6 since the 28th October. it is therefore not recommended to upgrade your distribution currently as piLogger is not yet ready for PHP 5.6.

**Comment by maglub** [comment]
Ops!
Do you have any output or notion on what is bad?

**Comment by do3meli** [comment]
actually i think it is fully working with PHP 5.6. i figured out a different issue #142 which is not related to the PHP version.
