### ISSUE TITLE
Disable 1-wire TCP server, http daemon, ftp server in setup.sh

### ISSUE THREAD

**Issue by maglub** [maglub/piLogger#143]
No need for anything but /mnt/1wire. The other features should be disabled

**Comment by do3meli** [comment]
how could that be achieved the best way? 
removing the files in `/etc/init.d/` directory or adjusting the file `/etc/owfs.conf `

**Comment by maglub** [comment]
sudo update-rc.d owftpd disable
sudo update-rc.d owhttpd disable
sudo update-rc.d owserver disable

**Comment by do3meli** [comment]
on my setup here these ow* services are not even running so i am wondering if that is really needed:

```
pi@domopi3 ~/piLogger $ netstat -an | grep 2121 | grep -v grep
pi@domopi3 ~/piLogger $ netstat -an | grep 2120 | grep -v grep
pi@domopi3 ~/piLogger $ netstat -an | grep 4304 | grep -v grep
```
the only thing running is owfs:
```
pi@domopi3 ~/piLogger $ ps -ef | grep ow | grep -v grep
root       605     1  0 Oct21 ?        00:20:25 /usr/lib/owfs/owfs -c /etc/owfs.conf --i2c=ALL:ALL --allow_other /mnt/1wire/
```
is that different on your setup?

**Comment by maglub** [comment]
I mainly see them when I reboot a rpi and have a scren/console connected.

They are not needed, sp we could just as well make sure to disable them.
