### ISSUE TITLE
Feature: optional remote logging script directory

### ISSUE THREAD

**Issue by maglub** [maglub/piLogger#53]
Idea:

Add a directory, i.e remote-logging.d, where scripts can be put that will each be called to send data to somewhere.

The scripts will all be called as with the parameters $1 $2 and $3 as:

```
script_to_run timestamp sensor data
```

Optionally, we can set a number of environment variables, to enrich the possible data to send.

* Device name
* Device id
* Sensor id
* Data
* Timestamp
* etc...

This would simplify the integration with other environments where we might want to send data, like:

* If this than that (http://ifttt.com), http://en.wikipedia.org/wiki/IFTTT
* https://shiftr.io
* Other piLoggers
* piLogger in the cloud

**Comment by do3meli** [comment]
this is closed now
