### ISSUE TITLE
After new REST API, remote logging does not work

### ISSUE THREAD

**Issue by maglub** [maglub/piLogger#71]
I forgot that the remote logging uses the script http://asdf/api/sensor/<id>/set/temperature/<temperature>

I have temporarily fixed this with an ugly "GET" route in ~/api/rest.php, but this should be changed to a PUT route at: http://asdf/api/sensor/<id>/temperature

**Comment by do3meli** [comment]
we could get rid of the following few lines of code sooner or later:
https://github.com/maglub/piLogger/blob/master/html/api/rest.php#L84-L90

the new put route has been implemented already:
https://github.com/maglub/piLogger/blob/master/html/api/rest.php#L92-L117
