### ISSUE TITLE
setup.sh should use /etc/default/locale

### ISSUE THREAD

**Issue by do3meli** [maglub/piLogger#76]
instead of using bash profile variables the locale setting should be done in /etc/default/locale. this file is getting read by the login process and therefore is parsed for every user not just pi.

**Comment by maglub** [comment]
Does setup really touch the .bash_profile itself or just giving a hint on what could be put there?

In any case, /etc/default/locale is a better place for the licale setting.

**Comment by do3meli** [comment]
To me it really looks like it is touching bash_profile:
