### ISSUE TITLE
default cronjob does not match default plot groups

### ISSUE THREAD

**Issue by do3meli** [maglub/piLogger#77]
the default plot groups are:

* 12h
* 24h
* 168h

but the default cronjob in the `readme.md` file are create new cached images for the following time frames:

* 24h
* 48h
* 168h

**Comment by maglub** [comment]
Ok, we should update the readme

**Comment by do3meli** [comment]
Actually i think we have to update the file in etc/cronjob as this is the one that we copy over to the local cronjob file.

In addition to that i think the readme needs to be updated anyway as this step was automated during setup as far as i remember. No need to copy paste anyhing...
