### ISSUE TITLE
Add devices page with sparklines

### ISSUE THREAD

**Issue by maglub** [maglub/piLogger#79]
The "devices page" should contain a list of the connected devices, their types, and a sparkline showing the last 24 hours (or so).

# References

* https://en.wikipedia.org/wiki/Sparkline
* http://omnipotent.net/jquery.sparkline/#s-about
* Sparklines at Highcharts: http://www.highcharts.com/demo/sparkline
* http://www.amcharts.com/demos/micro-charts-sparklines/

**Comment by maglub** [comment]
First release with sparklines done.

**Comment by do3meli** [comment]
we have sparklines added so far - so closing this issue here
