### ISSUE TITLE
upgrade should check for php5-rrd package

### ISSUE THREAD

**Issue by do3meli** [maglub/piLogger#87]
there should be a new version upgrade that checks if the php5-rrd package has been installed. this package will be installed via `setup.sh` but not if one chooses to pull the git and only run `upgrade.sh`. The php5-rrd package is needed since commit 617c952b4d1e5a8ced0c825658d8841b8f4da059

**Comment by maglub** [comment]
New release fixes this. 122f0dc9223ac5099b4f7960f07c75cd04c302dc
