### ISSUE TITLE
Feature: Refine backup/restore - restore to new SD card

### ISSUE THREAD

**Issue by maglub** [maglub/piLogger#9]
* Feature: easy restore of old backup to new SD card

Needed for a successful restore:

* $baseDir/etc/piLogger.conf
* Modified files in $baseDir/html
* Sensor data in *.rrd files -> /var/piLogger/db/*.rrd
* app.sqlite3 database -> /var/piLogger/db/app.sqlite3

```
cd $baseDir ; # cd ~/piLogger
git status | grep modified | awk -F":" '{print $NF}' | sed -e 's/^ *//' | grep "^html"
```

**Comment by maglub** [comment]
Needed for a successful restore:

* rrd files -> /var/piLogger/db
* app.sqlite3 database -> /var/piLogger/db

What about any changes to the html/php files?

**Comment by do3meli** [comment]
you can get any status of html/php files from the git repo if needed. you just need to know which commit correlates to which .rrd file

**Comment by maglub** [comment]
? what do you mean with the comment about which .rrd file? No rrd files are in git.

The main question is what to do about modified html files, if this should be backed up or not.

**Comment by do3meli** [comment]
all the modified html files you can get from git again, or am i missing something?
by this sentence i mean: you need to know from which date the backup is - so you can find the html files in git that were at this point in time active.

**Comment by maglub** [comment]
Got a bit confused when you mentioned ".rrd" files. So what you suggest is to backup files in the html directory that has changed.

List files in html to backup:
```
cd $baseDir ; # cd ~/piLogger
git status | grep modified | awk -F":" '{print $NF}' | sed -e 's/^ *//' | grep "^html"
```

**Comment by maglub** [comment]
Tested:

* ~/piLogger/bin/backup.sh
* Fresh install on new SD card
* Copy content of the backup.tgz file into /var/lib/piLogger/db
* Run ~/piLogger/bin/refreshCaches

This will leave you with a fresh install with your old data.

Todo: document this

**Comment by maglub** [comment]
Updated the README.md file, but forgot to mention this issue in the commit message.
