### ISSUE TITLE
add hostname to header

### ISSUE THREAD

**Issue by do3meli** [maglub/piLogger#91]
when switching between multiple piLogger installation in the browser it can get quite confusing.
therefore i suggest to add the hostname to the top left title. something like: `piLogger @ %hostname%`

**Comment by maglub** [comment]
#91 great idea, perhaps also with a configurable color of the top banner

**Comment by do3meli** [comment]
could be usefull: http://help.slimframework.com/discussions/questions/954-twig-getenvironment-function-no-longer-available-using-slim-views
