### ISSUE TITLE
upgrade should check for fails

### ISSUE THREAD

**Issue by do3meli** [maglub/piLogger#98]
we do upgrade the version even if an upgrade fails. we may should not do that and exit the upgrade immediately not that the upgrade after the failed one will be executed.

**Comment by maglub** [comment]
Actually, we do not upgrade the version if the upgrade fails.

In the piLogger_upgrade() function in functions-upgrade, we check the rc:

```
  piLogger_doUpgrade_${fromVersion}_to_${toVersion}
  local rc=$?

  [ $rc -eq 0 ] && { piLogger_setInstalledVersion "$toVersion" ; echo "    - Success" ; }
  [ $rc -ne 0 ] && { echo "    - FAILED" ; return 1 ; }
```

We should take care and return the proper return code from the upgrade functions.

**Comment by do3meli** [comment]
should we then maybe update the existing upgrade functions and make sure they return status codes correctly?

**Comment by maglub** [comment]
I would say that since we have gotten much better at error handling in later releases, we should just close this ticket and aim to take care of exceptions in the functions-upgrade and upgrade.sh from now on.
